# @package habitat.dataset
defaults:
  - /habitat/dataset: dataset_config_schema
  - _self_

type: ObjectNav-v1
split: val_mini
data_path: habitat-challenge-data/data/datasets/objectnav/hm3d/v2/{split}/{split}.json.gz
scenes_dir: habitat-challenge-data/data/scene_datasets/