objects:
  - name: goal0|0
    expr_type: rigid_obj_type
  - name: TARGET_goal0|0
    expr_type: goal_type
  - name: ROBOT_0
    expr_type: robot_type

goal:
  expr_type: AND
  sub_exprs:
    - at(goal0|0,TARGET_goal0|0)
    - not_holding(ROBOT_0)

stage_goals:
  stage_0_5:
    expr_type: AND
    sub_exprs:
      - holding(goal0|0, ROBOT_0)
  stage_1:
    expr_type: AND
    sub_exprs:
      - at(goal0|0,TARGET_goal0|0)

solution:
  - nav(goal0|0, ROBOT_0)
  - pick(goal0|0, ROBOT_0)
  - nav(TARGET_goal0|0, ROBOT_0)
  - place(goal0|0, TARGET_goal0|0, ROBOT_0)
